### ISSUE TITLE
Is SQL injection really necessary when setting parameters for data source?

### ISSUE THREAD

**Issue by EitanBlumin** [ststeiger/ReportViewerWrapper#1]
Is this SQL injection really necessary?
Isn't it possible to use proper parameterization when setting up the data source?

https://github.com/ststeiger/ReportViewerWrapper/blob/7c936e17f72932a61bde221517c311eaeb8c3109/Embedded2016/Umzugsmitteilung.cs#L65

**Comment by ststeiger** [comment]
Sure it is, that was just quick-n-dirty for testing. 
And as it is, sometimes, some prototypes that shouldn't go live, go live;
with the full knowledge of the developer :camel:

**Comment by EitanBlumin** [comment]
Okay thanks for clarification
